const data = {
  products: [
    {
      _id: 1,
      name: "Meuleuse Bosh",
      category: "tools",
      image: "./images/meuleuse.jpg",
      price: 89,
      brand: "Bosh",
      rating: 4.5,
      numReviews: 10,
      description: "Meuleuse d'angle filaire 125mm",
    },
    {
      _id: 2,
      name: "Perceuse Bosh",
      category: "tools",
      image: "./images/perceuse.jpg",
      price: 139,
      brand: "Bosh",
      rating: 4,
      numReviews: 17,
      description: "Perceuse Bosh sans fil 18V",
    },
    {
      _id: 3,
      name: "Marteau Facom",
      category: "tools",
      image: "./images/marteau.jpg",
      price: 25,
      brand: "Facom",
      rating: 5,
      numReviews: 23,
      description: "Marteau Facom bi-matière",
    },
    {
      _id: 4,
      name: "Meuleuse Bosh",
      category: "tools",
      image: "./images/tournevis.jpg",
      price: 19.9,
      brand: "Facom",
      rating: 4.5,
      numReviews: 7,
      description: 'Tournevis cruciforme "Expert" by Facom',
    },
    {
      _id: 5,
      name: "Citreuse à galets",
      category: "machinery",
      image: "./images/cintreuse.jpg",
      price: 490,
      brand: "PRP",
      rating: 4,
      numReviews: 13,
      description: "Cintreuse à galets manuelle",
    },
    {
      _id: 6,
      name: "Plieuse",
      category: "machinery",
      image: "./images/plieuse.jpg",
      price: 980,
      brand: "Metalkraft",
      rating: 5,
      numReviews: 8,
      description: "Plieuse de tôle (1,5mm maximum)",
    },
    {
      _id: 7,
      name: "Tube carré en acier 40mm x 40mm",
      category: "steel",
      image: "./images/tube.jpg",
      price: 13,
      brand: "Decons",
      rating: 5,
      numReviews: 13,
      description: "Tube carré acier: 40mm x 40mm, 1000mm linéaire",
    },
    {
      _id: 8,
      name: "Tube rond en acier 40mm",
      category: "steel",
      image: "./images/tube-rond.jpg",
      price: 13,
      brand: "Decons",
      rating: 5,
      numReviews: 16,
      description: "Tube rond acier: 40mm de diamètre, 1000mm linéaire",
    },
    {
      _id: 9,
      name: "Tôle acier 2mm",
      category: "steel",
      image: "./images/tôle.jpg",
      price: 35,
      brand: "Decons",
      rating: 5,
      numReviews: 21,
      description: "Tôle acier: épaisseur 2mm, 1000mm x 1000mm",
    },
    {
      _id: 10,
      name: "Poste à souder",
      category: "welding",
      image: "./images/poste.jpg",
      price: 13,
      brand: "GYS",
      rating: 3.5,
      numReviews: 10,
      description: "Poste à souder à l'arc",
    },
    {
      _id: 11,
      name: "2 x Pack electrodes enrobées",
      category: "welding",
      image: "./images/baguette-soudure.jpg",
      price: 39,
      brand: "GYS",
      rating: 4,
      numReviews: 26,
      description: "Lot de deux boites d'électrodes: 1 x 2,5mm et 3,2mm",
    },
    {
      _id: 12,
      name: "Masque de soudeur",
      category: "welding",
      image: "./images/masque-soudure.jpg",
      price: 35,
      brand: "GYS",
      rating: 4,
      numReviews: 31,
      description: "Masque de soudure de type électronique",
    },
    {
      _id: 13,
      name: "Gant de soudeur",
      category: "welding",
      image: "./images/gant-soudeur.jpg",
      price: 15,
      brand: "GYS",
      rating: 3.5,
      numReviews: 12,
      description: "Gant de soudeur en cuir",
    },
  ],
};

export default data;
